### ISSUE TITLE
Fails on long documents if include_docs=true

### ISSUE THREAD

**Issue by ig3** [soukand/couchdb-change-events#5]
The current code doesn't handle the case that a change in the feed runs off the end of a chunk from the http request. In this case, one or more additional chunks are required to complete the change. As-is, the attempt to parse the partial JSON fails.

**Comment by ig3** [comment]
I have submitted a pull request for your consideration. Probably not very elegant, but it works for me and should clarify the issue.

**Comment by brailateo** [comment]
Fails also on many updates , on small documents. 
When tried to process over 10.000 changes from the first, it crashes randomly:

undefined:1
{"seq":488,"id":"e7de5f59-f1e7-4a6c-b9b8-1467944b3a1a","changes":[{"rev":"1-0d9cc3ce8e2a84749c2cb3a1def87ea2"}],"doc":{"_id":"e7de5f59-f1e7-4a6c-b9b8-1467944b3a1a","_rev":"1-0d9cc3ce8e2a84749c2cb3a1def87ea2","nume":"Gelu","prenume":"Popa","strada":" str pomului nr21","numar":"21
                                                                                                                                                                                                                                                                                                                                

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at CouchdbChangeEvents.onCouchdbChange (/home/liviu/node_modules/couchdb-change-events/src/couchdb-change-events.js:111:30)
    at IncomingMessage.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at IncomingMessage.Readable.push (_stream_readable.js:212:10)
    at HTTPParser.parserOnBody (_http_common.js:132:24)
    at Socket.socketOnData (_http_client.js:469:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)

**Comment by PPrasai** [comment]
@brailateo Hi. Did you resolve this issue. Same thing is happening with my watcher.
